version: '3.8'

services:
  db:
    image: postgres:16
    restart: no
    environment:
      POSTGRES_DB: bd_crud
      POSTGRES_USER: bd_crud_user
      POSTGRES_PASSWORD: 0xKmiYNj69yySidke2iI4rmnsFjFlJEi
    ports:
      - "5432:5432"  # Expone el puerto 5432 de PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Guarda los datos de la base de datos
    networks:
      - bloc_crud  # Conecta el contenedor a la red externa

  crud_app:
    build: .
    ports:
      - "5008:5008"  # Mapea el puerto 5008 del contenedor al puerto 5008 de la máquina local
    depends_on:
      - db  # Asegura que el contenedor de la base de datos se inicie antes
    environment:
      - DATABASE_URL=postgresql://bd_crud_user:0xKmiYNj69yySidke2iI4rmnsFjFlJEi@dpg-cvotcabe5dus73c8bf1g-a.oregon-postgres.render.com/bd_crud  # Nueva URL de conexión
    volumes:
      - .:/app  # Monta el directorio actual en el contenedor para desarrollo en vivo
    restart: always  # Reinicia el contenedor automáticamente si se detiene
    networks:
      - bloc_crud  # Conecta el contenedor a la red externa

volumes:
  postgres_data:  # Define un volumen persistente para PostgreSQL

networks:
  bloc_crud:
    external: true  # Usa una red externa ya existente

